### ISSUE TITLE
Don't pass in URL if we don't need to

### ISSUE THREAD

**Issue by naterush** [saga-vcs/saga-excel#3]
https://github.com/saga-vcs/saga-excel/blob/ab96ac60dfcf80eade8021aaa86bf9b458a9c485/src/taskpane/components/saga/commit.js#L96

Since the URL for these functions that spawn the dialogue is always the same, let's move it into the functions. 

If we have a general functions for displaying dialogue boxes and getting back values, then good to make the URL the parameter. Otherwise, keeping the URL as a parameter is more work for the caller for no benefit.

**Comment by aarondr77** [comment]
Resolved.
