### ISSUE TITLE
Move files out of mongo (or clear mongo).

### ISSUE THREAD

**Issue by naterush** [saga-vcs/saga-excel#54]
I do not think we have a space quota on Document DB (the AWS Mongo replacement), but it is more expensive to store files there than it is to store them on S3.

We should figure out how to store files on S3 and serve them from the lambda functions. The meta-data for the project (commits, etc) would all still be stored in the DB for fast access, but when the user wants to download files, they get forwarded to S3.

**Comment by aarondr77** [comment]
Nate transferred us completely out of Mongo on 6/6/20
