### ISSUE TITLE
Bolded cells do not merge

### ISSUE THREAD

**Issue by jake-stack** [saga-vcs/saga-excel#56]
1. I opened excel and inserted the add-in
2. I filed some cells with numbers
3. I merged these edits to master- worked fine
4. then bolded two cells and tried to merge those edits to master--the numbers in the cells merge successfully but the bolding disappears in personal and master

**Comment by naterush** [comment]
@jake-stack thanks for the report. @aarondr77 let's get some formatting tests up in here - so we can assess the situation.

**Comment by aarondr77** [comment]
Formatting is working on my computer. I added two formatting tests to the merge test suite.

**Comment by naterush** [comment]
@jake-stack let's debug this on your computer today, and see if we can figure out what's up.

**Comment by aarondr77** [comment]
Bug diagnosis: 

- If I  create a new project, add something to A1 and then bold it, and then merge, it does not bold. - If I create a new project, add a second page, add to A1 on both pages and then bold A1 on the second page, and then merge, A1 on the second page is bold. If I then bold A1 on the first page and merge, A1 on the first page is bold. 
- If I create a new project, add a second page, add A1 to both pages and then bold A1 on both pages, and then merge. Only the A1 on the second page is bold. 

Ideas:

The event handler for formatting is not getting registered on the creation of the project.

**Comment by naterush** [comment]
It's either that or something messed up w/ sheet ids. Easily checkable by printing the saved formatting events during the merge, and see if they are stored.

**Comment by naterush** [comment]
This was addressed, and is now tested.
